FROM matomo:latest

ARG MYSQL_PASSWORD
ARG MYSQL_DATABASE
ARG MYSQL_USER
ARG MATOMO_DATABASE_ADAPTER
ARG MATOMO_DATABASE_TABLES_PREFIX
ARG MATOMO_DATABASE_USERNAME
ARG MATOMO_DATABASE_PASSWORD
ARG MATOMO_DATABASE_DBNAME
ARG MARIADB_AUTO_UPGRADE
ARG MARIADB_INITDB_SKIP_TZINFO

ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}
ENV MYSQL_DATABASE=${MYSQL_DATABASE}
ENV MYSQL_USER=${MYSQL_USER}
ENV MATOMO_DATABASE_ADAPTER=${MATOMO_DATABASE_ADAPTER}
ENV MATOMO_DATABASE_TABLES_PREFIX=${MATOMO_DATABASE_TABLES_PREFIX}
ENV MATOMO_DATABASE_USERNAME=${MATOMO_DATABASE_USERNAME}
ENV MATOMO_DATABASE_PASSWORD=${MATOMO_DATABASE_PASSWORD}
ENV MATOMO_DATABASE_DBNAME=${MATOMO_DATABASE_DBNAME}
ENV MARIADB_AUTO_UPGRADE=${MARIADB_AUTO_UPGRADE}
ENV MARIADB_INITDB_SKIP_TZINFO=${MARIADB_INITDB_SKIP_TZINFO}
